import {LightLevel, Toxicity} from '@/constants/plantAttributes'
import {WaterLevel} from '@/constants/plantAttributes'
import {SoilType} from '@/constants/plantAttributes'
import {Humidity} from '@/constants/plantAttributes'


export const plantTypes = [
  {
    plantName: 'Aloe Vera',
    latinName: 'Aloe vera',
    img: 'aloeVera.webp',
    light: LightLevel.high,
    water: WaterLevel.low,
    soil: SoilType.dry,
    humidity: Humidity.low,
    toxicity: Toxicity.edible,
    room: '',
  },
  {
    plantName: 'Golden Pothos',
    latinName: 'Epipremnum aureum',
    img: 'goldenPothos.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.low,
    soil: SoilType.mediumDry,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Snake Plant',
    latinName: 'Dracaena trifasciata',
    img: 'snakePlant.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.low,
    soil: SoilType.dry,
    humidity: Humidity.low,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Moth Orchid',
    latinName: 'Phalaenopsis amabilis',
    img: 'mothOrchid.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.low,
    soil: SoilType.mediumDry,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Peace Lily',
    latinName: 'Spathiphyllum cochlearispathum',
    img: 'peaceLily.webp',
    light: LightLevel.medium,
    water: WaterLevel.medium,
    soil: SoilType.moist,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.mediumToxic,
  },
  {
    plantName: 'Basil',
    latinName: 'Ocimum Basilicum',
    img: 'basil.webp',
    light: LightLevel.high,
    water: WaterLevel.medium,
    soil: SoilType.moist,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.edible,
  },
  {
    plantName: 'African Violet',
    latinName: 'Saintpaulia Ionantha',
    img: 'africanViolet.webp',
    light: LightLevel.high,
    water: WaterLevel.high,
    soil: SoilType.moist,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Jade Plant',
    latinName: 'Crassula ovata',
    img: 'jadePlant.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.medium,
    soil: SoilType.dry,
    humidity: Humidity.low,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Spider Plant',
    latinName: 'Chlorophytum comosum',
    img: 'spiderPlant.webp',
    light: LightLevel.medium,
    water: WaterLevel.medium,
    soil: SoilType.mediumDry,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Rubber Plant',
    latinName: 'Ficus elastica',
    img: 'rubberPlant.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.high,
    soil: SoilType.mediumDry,
    humidity: Humidity.low,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Dumb Cane',
    latinName: 'Dieffenbachia',
    img: 'dumbCane.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.high,
    soil: SoilType.mediumDry,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Monstera Deliciosa',
    latinName: 'Monstera deliciosa',
    img: 'monsteraDeliciosa.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.medium,
    soil: SoilType.mediumDry,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Rosemary',
    latinName: 'Salvia Rosmarinus',
    img: 'rosemary.webp',
    light: LightLevel.high,
    water: WaterLevel.medium,
    soil: SoilType.dry,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.edible,
  },
  {
    plantName: 'Umbrella Plant',
    latinName: 'Schefflera actinophylla',
    img: 'umbrellaPlant.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.medium,
    soil: SoilType.moist,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.mediumToxic,
  },
  {
    plantName: 'Money Tree',
    latinName: 'Guiana chestnut',
    img: 'moneyTree.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.high,
    soil: SoilType.mediumDry,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'English Ivy',
    latinName: 'Hedera helix',
    img: 'englishIvy.webp',
    light: LightLevel.medium,
    water: WaterLevel.medium,
    soil: SoilType.moist,
    humidity: Humidity.medium,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'ZZ Plant',
    latinName: 'Zomioculas zamiifolia',
    img: 'zzPlant.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.low,
    soil: SoilType.mediumDry,
    humidity: Humidity.low,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Boston Fern',
    latinName: 'Nephrolepis exaltata',
    img: 'bostonFern.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.high,
    soil: SoilType.mediumDry,
    humidity: Humidity.high,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Areca Palm',
    latinName: 'Dypsis lutescens',
    img: 'arecaPalm.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.medium,
    soil: SoilType.mediumDry,
    humidity: Humidity.mediumHigh,
    toxicity: Toxicity.nonToxic,
  },
  {
    plantName: 'Fiddle Leaf',
    latinName: 'Ficus lyrata',
    img: 'fiddleLeaf.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.medium,
    soil: SoilType.mediumDry,
    humidity: Humidity.medium,
    toxicity: Toxicity.mediumToxic,
  },
  {
    plantName: 'Pilea',
    latinName: 'Pilea peperomoides',
    img: 'pilea.webp',
    light: LightLevel.mediumHigh,
    water: WaterLevel.medium,
    soil: SoilType.mediumDry,
    humidity: Humidity.low,
    toxicity: Toxicity.nonToxic,
  },
]